apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ec5u8os0f-dotnet-basic
  janus-idp.io/tekton: ec5u8os0f-dotnet-basic
  backstage.io/kubernetes-id: ec5u8os0f-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ec5u8os0f-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
